/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as DonarRouteImport } from './routes/donar'
import { Route as DesaparecidosRouteImport } from './routes/desaparecidos'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportesIdRouteImport } from './routes/reportes.$id'
import { Route as ApiReportsDotgeojsonRouteImport } from './routes/api/reports[.]geojson'
import { Route as ApiReportsDotcsvRouteImport } from './routes/api/reports[.]csv'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarRoute = DonarRouteImport.update({
  id: '/donar',
  path: '/donar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosRoute = DesaparecidosRouteImport.update({
  id: '/desaparecidos',
  path: '/desaparecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIdRoute = ReportesIdRouteImport.update({
  id: '/reportes/$id',
  path: '/reportes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsDotgeojsonRoute = ApiReportsDotgeojsonRouteImport.update({
  id: '/api/reports.geojson',
  path: '/api/reports.geojson',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsDotcsvRoute = ApiReportsDotcsvRouteImport.update({
  id: '/api/reports.csv',
  path: '/api/reports.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/reportar': typeof ReportarRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/reportar': typeof ReportarRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/reportar': typeof ReportarRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/reportar'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/reportes/$id'
    | '/api/public/media/$'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/reportar'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/reportes/$id'
    | '/api/public/media/$'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/reportar'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/reportes/$id'
    | '/api/public/media/$'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CreditosRoute: typeof CreditosRoute
  DesaparecidosRoute: typeof DesaparecidosRoute
  DonarRoute: typeof DonarRoute
  EstadisticasRoute: typeof EstadisticasRoute
  ReportarRoute: typeof ReportarRoute
  ApiReportsDotcsvRoute: typeof ApiReportsDotcsvRoute
  ApiReportsDotgeojsonRoute: typeof ApiReportsDotgeojsonRoute
  ReportesIdRoute: typeof ReportesIdRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar': {
      id: '/donar'
      path: '/donar'
      fullPath: '/donar'
      preLoaderRoute: typeof DonarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos': {
      id: '/desaparecidos'
      path: '/desaparecidos'
      fullPath: '/desaparecidos'
      preLoaderRoute: typeof DesaparecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/$id': {
      id: '/reportes/$id'
      path: '/reportes/$id'
      fullPath: '/reportes/$id'
      preLoaderRoute: typeof ReportesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports.geojson': {
      id: '/api/reports.geojson'
      path: '/api/reports.geojson'
      fullPath: '/api/reports.geojson'
      preLoaderRoute: typeof ApiReportsDotgeojsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports.csv': {
      id: '/api/reports.csv'
      path: '/api/reports.csv'
      fullPath: '/api/reports.csv'
      preLoaderRoute: typeof ApiReportsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CreditosRoute: CreditosRoute,
  DesaparecidosRoute: DesaparecidosRoute,
  DonarRoute: DonarRoute,
  EstadisticasRoute: EstadisticasRoute,
  ReportarRoute: ReportarRoute,
  ApiReportsDotcsvRoute: ApiReportsDotcsvRoute,
  ApiReportsDotgeojsonRoute: ApiReportsDotgeojsonRoute,
  ReportesIdRoute: ReportesIdRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
