/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TsunamiRouteImport } from './routes/tsunami'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as QueEsRouteImport } from './routes/que-es'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NecesidadesRouteImport } from './routes/necesidades'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as DonarRouteImport } from './routes/donar'
import { Route as DesaparecidosRouteImport } from './routes/desaparecidos'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReportesIdRouteImport } from './routes/reportes.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiTsunamiRouteImport } from './routes/api/tsunami'
import { Route as ApiReportsDotgeojsonRouteImport } from './routes/api/reports[.]geojson'
import { Route as ApiReportsDotcsvRouteImport } from './routes/api/reports[.]csv'
import { Route as ApiPatientsDotjsonRouteImport } from './routes/api/patients[.]json'
import { Route as ApiPatientsDotcsvRouteImport } from './routes/api/patients[.]csv'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiOffersDotjsonRouteImport } from './routes/api/offers[.]json'
import { Route as ApiOffersDotgeojsonRouteImport } from './routes/api/offers[.]geojson'
import { Route as ApiOffersDotcsvRouteImport } from './routes/api/offers[.]csv'
import { Route as ApiNeedsDotjsonRouteImport } from './routes/api/needs[.]json'
import { Route as ApiNeedsDotgeojsonRouteImport } from './routes/api/needs[.]geojson'
import { Route as ApiNeedsDotcsvRouteImport } from './routes/api/needs[.]csv'
import { Route as ApiMissingPersonsDotjsonRouteImport } from './routes/api/missing-persons[.]json'
import { Route as ApiMissingPersonsDotgeojsonRouteImport } from './routes/api/missing-persons[.]geojson'
import { Route as ApiMissingPersonsDotcsvRouteImport } from './routes/api/missing-persons[.]csv'
import { Route as ApiHealthCentersDotjsonRouteImport } from './routes/api/health-centers[.]json'
import { Route as ApiHealthCentersDotgeojsonRouteImport } from './routes/api/health-centers[.]geojson'
import { Route as ApiHealthCentersDotcsvRouteImport } from './routes/api/health-centers[.]csv'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as ApiCategoriesDotjsonRouteImport } from './routes/api/categories[.]json'
import { Route as AdminObservabilidadRouteImport } from './routes/admin.observabilidad'
import { Route as AdminInteropRouteImport } from './routes/admin.interop'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicReportsRouteImport } from './routes/api/public/reports'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGeocodeRouteImport } from './routes/api/public/geocode'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPushManageRouteImport } from './routes/api/public/push/manage'
import { Route as ApiPublicPushBroadcastRouteImport } from './routes/api/public/push/broadcast'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicHooksIngestUsgsRouteImport } from './routes/api/public/hooks/ingest-usgs'
import { Route as ApiPublicAdminHealthRouteImport } from './routes/api/public/admin/health'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TsunamiRoute = TsunamiRouteImport.update({
  id: '/tsunami',
  path: '/tsunami',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const QueEsRoute = QueEsRouteImport.update({
  id: '/que-es',
  path: '/que-es',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesidadesRoute = NecesidadesRouteImport.update({
  id: '/necesidades',
  path: '/necesidades',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarRoute = DonarRouteImport.update({
  id: '/donar',
  path: '/donar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosRoute = DesaparecidosRouteImport.update({
  id: '/desaparecidos',
  path: '/desaparecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIdRoute = ReportesIdRouteImport.update({
  id: '/reportes/$id',
  path: '/reportes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTsunamiRoute = ApiTsunamiRouteImport.update({
  id: '/tsunami',
  path: '/tsunami',
  getParentRoute: () => ApiRoute,
} as any)
const ApiReportsDotgeojsonRoute = ApiReportsDotgeojsonRouteImport.update({
  id: '/reports.geojson',
  path: '/reports.geojson',
  getParentRoute: () => ApiRoute,
} as any)
const ApiReportsDotcsvRoute = ApiReportsDotcsvRouteImport.update({
  id: '/reports.csv',
  path: '/reports.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPatientsDotjsonRoute = ApiPatientsDotjsonRouteImport.update({
  id: '/patients.json',
  path: '/patients.json',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPatientsDotcsvRoute = ApiPatientsDotcsvRouteImport.update({
  id: '/patients.csv',
  path: '/patients.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => ApiRoute,
} as any)
const ApiOffersDotjsonRoute = ApiOffersDotjsonRouteImport.update({
  id: '/offers.json',
  path: '/offers.json',
  getParentRoute: () => ApiRoute,
} as any)
const ApiOffersDotgeojsonRoute = ApiOffersDotgeojsonRouteImport.update({
  id: '/offers.geojson',
  path: '/offers.geojson',
  getParentRoute: () => ApiRoute,
} as any)
const ApiOffersDotcsvRoute = ApiOffersDotcsvRouteImport.update({
  id: '/offers.csv',
  path: '/offers.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiNeedsDotjsonRoute = ApiNeedsDotjsonRouteImport.update({
  id: '/needs.json',
  path: '/needs.json',
  getParentRoute: () => ApiRoute,
} as any)
const ApiNeedsDotgeojsonRoute = ApiNeedsDotgeojsonRouteImport.update({
  id: '/needs.geojson',
  path: '/needs.geojson',
  getParentRoute: () => ApiRoute,
} as any)
const ApiNeedsDotcsvRoute = ApiNeedsDotcsvRouteImport.update({
  id: '/needs.csv',
  path: '/needs.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiMissingPersonsDotjsonRoute =
  ApiMissingPersonsDotjsonRouteImport.update({
    id: '/missing-persons.json',
    path: '/missing-persons.json',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiMissingPersonsDotgeojsonRoute =
  ApiMissingPersonsDotgeojsonRouteImport.update({
    id: '/missing-persons.geojson',
    path: '/missing-persons.geojson',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiMissingPersonsDotcsvRoute = ApiMissingPersonsDotcsvRouteImport.update({
  id: '/missing-persons.csv',
  path: '/missing-persons.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiHealthCentersDotjsonRoute = ApiHealthCentersDotjsonRouteImport.update({
  id: '/health-centers.json',
  path: '/health-centers.json',
  getParentRoute: () => ApiRoute,
} as any)
const ApiHealthCentersDotgeojsonRoute =
  ApiHealthCentersDotgeojsonRouteImport.update({
    id: '/health-centers.geojson',
    path: '/health-centers.geojson',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiHealthCentersDotcsvRoute = ApiHealthCentersDotcsvRouteImport.update({
  id: '/health-centers.csv',
  path: '/health-centers.csv',
  getParentRoute: () => ApiRoute,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiRoute,
} as any)
const ApiCategoriesDotjsonRoute = ApiCategoriesDotjsonRouteImport.update({
  id: '/categories.json',
  path: '/categories.json',
  getParentRoute: () => ApiRoute,
} as any)
const AdminObservabilidadRoute = AdminObservabilidadRouteImport.update({
  id: '/admin/observabilidad',
  path: '/admin/observabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInteropRoute = AdminInteropRouteImport.update({
  id: '/admin/interop',
  path: '/admin/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportsRoute = ApiPublicReportsRouteImport.update({
  id: '/public/reports',
  path: '/public/reports',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/public/health',
  path: '/public/health',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicGeocodeRoute = ApiPublicGeocodeRouteImport.update({
  id: '/public/geocode',
  path: '/public/geocode',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/public/contact',
  path: '/public/contact',
  getParentRoute: () => ApiRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/public/telegram/webhook',
    path: '/public/telegram/webhook',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicPushManageRoute = ApiPublicPushManageRouteImport.update({
  id: '/public/push/manage',
  path: '/public/push/manage',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicPushBroadcastRoute = ApiPublicPushBroadcastRouteImport.update({
  id: '/public/push/broadcast',
  path: '/public/push/broadcast',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/public/media/$',
  path: '/public/media/$',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicHooksIngestUsgsRoute =
  ApiPublicHooksIngestUsgsRouteImport.update({
    id: '/public/hooks/ingest-usgs',
    path: '/public/hooks/ingest-usgs',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicAdminHealthRoute = ApiPublicAdminHealthRouteImport.update({
  id: '/public/admin/health',
  path: '/public/admin/health',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/necesidades': typeof NecesidadesRoute
  '/ofertas': typeof OfertasRoute
  '/pacientes': typeof PacientesRoute
  '/que-es': typeof QueEsRoute
  '/reportar': typeof ReportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunami': typeof TsunamiRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/interop': typeof AdminInteropRoute
  '/admin/observabilidad': typeof AdminObservabilidadRoute
  '/api/categories.json': typeof ApiCategoriesDotjsonRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/health-centers.csv': typeof ApiHealthCentersDotcsvRoute
  '/api/health-centers.geojson': typeof ApiHealthCentersDotgeojsonRoute
  '/api/health-centers.json': typeof ApiHealthCentersDotjsonRoute
  '/api/missing-persons.csv': typeof ApiMissingPersonsDotcsvRoute
  '/api/missing-persons.geojson': typeof ApiMissingPersonsDotgeojsonRoute
  '/api/missing-persons.json': typeof ApiMissingPersonsDotjsonRoute
  '/api/needs.csv': typeof ApiNeedsDotcsvRoute
  '/api/needs.geojson': typeof ApiNeedsDotgeojsonRoute
  '/api/needs.json': typeof ApiNeedsDotjsonRoute
  '/api/offers.csv': typeof ApiOffersDotcsvRoute
  '/api/offers.geojson': typeof ApiOffersDotgeojsonRoute
  '/api/offers.json': typeof ApiOffersDotjsonRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/patients.csv': typeof ApiPatientsDotcsvRoute
  '/api/patients.json': typeof ApiPatientsDotjsonRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/api/tsunami': typeof ApiTsunamiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin/health': typeof ApiPublicAdminHealthRoute
  '/api/public/hooks/ingest-usgs': typeof ApiPublicHooksIngestUsgsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/push/broadcast': typeof ApiPublicPushBroadcastRoute
  '/api/public/push/manage': typeof ApiPublicPushManageRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/necesidades': typeof NecesidadesRoute
  '/ofertas': typeof OfertasRoute
  '/pacientes': typeof PacientesRoute
  '/que-es': typeof QueEsRoute
  '/reportar': typeof ReportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunami': typeof TsunamiRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/interop': typeof AdminInteropRoute
  '/admin/observabilidad': typeof AdminObservabilidadRoute
  '/api/categories.json': typeof ApiCategoriesDotjsonRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/health-centers.csv': typeof ApiHealthCentersDotcsvRoute
  '/api/health-centers.geojson': typeof ApiHealthCentersDotgeojsonRoute
  '/api/health-centers.json': typeof ApiHealthCentersDotjsonRoute
  '/api/missing-persons.csv': typeof ApiMissingPersonsDotcsvRoute
  '/api/missing-persons.geojson': typeof ApiMissingPersonsDotgeojsonRoute
  '/api/missing-persons.json': typeof ApiMissingPersonsDotjsonRoute
  '/api/needs.csv': typeof ApiNeedsDotcsvRoute
  '/api/needs.geojson': typeof ApiNeedsDotgeojsonRoute
  '/api/needs.json': typeof ApiNeedsDotjsonRoute
  '/api/offers.csv': typeof ApiOffersDotcsvRoute
  '/api/offers.geojson': typeof ApiOffersDotgeojsonRoute
  '/api/offers.json': typeof ApiOffersDotjsonRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/patients.csv': typeof ApiPatientsDotcsvRoute
  '/api/patients.json': typeof ApiPatientsDotjsonRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/api/tsunami': typeof ApiTsunamiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin/health': typeof ApiPublicAdminHealthRoute
  '/api/public/hooks/ingest-usgs': typeof ApiPublicHooksIngestUsgsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/push/broadcast': typeof ApiPublicPushBroadcastRoute
  '/api/public/push/manage': typeof ApiPublicPushManageRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/donar': typeof DonarRoute
  '/estadisticas': typeof EstadisticasRoute
  '/necesidades': typeof NecesidadesRoute
  '/ofertas': typeof OfertasRoute
  '/pacientes': typeof PacientesRoute
  '/que-es': typeof QueEsRoute
  '/reportar': typeof ReportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunami': typeof TsunamiRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/interop': typeof AdminInteropRoute
  '/admin/observabilidad': typeof AdminObservabilidadRoute
  '/api/categories.json': typeof ApiCategoriesDotjsonRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/health-centers.csv': typeof ApiHealthCentersDotcsvRoute
  '/api/health-centers.geojson': typeof ApiHealthCentersDotgeojsonRoute
  '/api/health-centers.json': typeof ApiHealthCentersDotjsonRoute
  '/api/missing-persons.csv': typeof ApiMissingPersonsDotcsvRoute
  '/api/missing-persons.geojson': typeof ApiMissingPersonsDotgeojsonRoute
  '/api/missing-persons.json': typeof ApiMissingPersonsDotjsonRoute
  '/api/needs.csv': typeof ApiNeedsDotcsvRoute
  '/api/needs.geojson': typeof ApiNeedsDotgeojsonRoute
  '/api/needs.json': typeof ApiNeedsDotjsonRoute
  '/api/offers.csv': typeof ApiOffersDotcsvRoute
  '/api/offers.geojson': typeof ApiOffersDotgeojsonRoute
  '/api/offers.json': typeof ApiOffersDotjsonRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/patients.csv': typeof ApiPatientsDotcsvRoute
  '/api/patients.json': typeof ApiPatientsDotjsonRoute
  '/api/reports.csv': typeof ApiReportsDotcsvRoute
  '/api/reports.geojson': typeof ApiReportsDotgeojsonRoute
  '/api/tsunami': typeof ApiTsunamiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/reportes/$id': typeof ReportesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin/health': typeof ApiPublicAdminHealthRoute
  '/api/public/hooks/ingest-usgs': typeof ApiPublicHooksIngestUsgsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/push/broadcast': typeof ApiPublicPushBroadcastRoute
  '/api/public/push/manage': typeof ApiPublicPushManageRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/necesidades'
    | '/ofertas'
    | '/pacientes'
    | '/que-es'
    | '/reportar'
    | '/sitemap.xml'
    | '/tsunami'
    | '/unsubscribe'
    | '/admin/interop'
    | '/admin/observabilidad'
    | '/api/categories.json'
    | '/api/docs'
    | '/api/health-centers.csv'
    | '/api/health-centers.geojson'
    | '/api/health-centers.json'
    | '/api/missing-persons.csv'
    | '/api/missing-persons.geojson'
    | '/api/missing-persons.json'
    | '/api/needs.csv'
    | '/api/needs.geojson'
    | '/api/needs.json'
    | '/api/offers.csv'
    | '/api/offers.geojson'
    | '/api/offers.json'
    | '/api/openapi.json'
    | '/api/patients.csv'
    | '/api/patients.json'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/api/tsunami'
    | '/email/unsubscribe'
    | '/reportes/$id'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/geocode'
    | '/api/public/health'
    | '/api/public/reports'
    | '/lovable/email/suppression'
    | '/api/public/admin/health'
    | '/api/public/hooks/ingest-usgs'
    | '/api/public/media/$'
    | '/api/public/push/broadcast'
    | '/api/public/push/manage'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/necesidades'
    | '/ofertas'
    | '/pacientes'
    | '/que-es'
    | '/reportar'
    | '/sitemap.xml'
    | '/tsunami'
    | '/unsubscribe'
    | '/admin/interop'
    | '/admin/observabilidad'
    | '/api/categories.json'
    | '/api/docs'
    | '/api/health-centers.csv'
    | '/api/health-centers.geojson'
    | '/api/health-centers.json'
    | '/api/missing-persons.csv'
    | '/api/missing-persons.geojson'
    | '/api/missing-persons.json'
    | '/api/needs.csv'
    | '/api/needs.geojson'
    | '/api/needs.json'
    | '/api/offers.csv'
    | '/api/offers.geojson'
    | '/api/offers.json'
    | '/api/openapi.json'
    | '/api/patients.csv'
    | '/api/patients.json'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/api/tsunami'
    | '/email/unsubscribe'
    | '/reportes/$id'
    | '/admin'
    | '/api/public/contact'
    | '/api/public/geocode'
    | '/api/public/health'
    | '/api/public/reports'
    | '/lovable/email/suppression'
    | '/api/public/admin/health'
    | '/api/public/hooks/ingest-usgs'
    | '/api/public/media/$'
    | '/api/public/push/broadcast'
    | '/api/public/push/manage'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/auth'
    | '/creditos'
    | '/desaparecidos'
    | '/donar'
    | '/estadisticas'
    | '/necesidades'
    | '/ofertas'
    | '/pacientes'
    | '/que-es'
    | '/reportar'
    | '/sitemap.xml'
    | '/tsunami'
    | '/unsubscribe'
    | '/admin/interop'
    | '/admin/observabilidad'
    | '/api/categories.json'
    | '/api/docs'
    | '/api/health-centers.csv'
    | '/api/health-centers.geojson'
    | '/api/health-centers.json'
    | '/api/missing-persons.csv'
    | '/api/missing-persons.geojson'
    | '/api/missing-persons.json'
    | '/api/needs.csv'
    | '/api/needs.geojson'
    | '/api/needs.json'
    | '/api/offers.csv'
    | '/api/offers.geojson'
    | '/api/offers.json'
    | '/api/openapi.json'
    | '/api/patients.csv'
    | '/api/patients.json'
    | '/api/reports.csv'
    | '/api/reports.geojson'
    | '/api/tsunami'
    | '/email/unsubscribe'
    | '/reportes/$id'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/geocode'
    | '/api/public/health'
    | '/api/public/reports'
    | '/lovable/email/suppression'
    | '/api/public/admin/health'
    | '/api/public/hooks/ingest-usgs'
    | '/api/public/media/$'
    | '/api/public/push/broadcast'
    | '/api/public/push/manage'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreditosRoute: typeof CreditosRoute
  DesaparecidosRoute: typeof DesaparecidosRoute
  DonarRoute: typeof DonarRoute
  EstadisticasRoute: typeof EstadisticasRoute
  NecesidadesRoute: typeof NecesidadesRoute
  OfertasRoute: typeof OfertasRoute
  PacientesRoute: typeof PacientesRoute
  QueEsRoute: typeof QueEsRoute
  ReportarRoute: typeof ReportarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TsunamiRoute: typeof TsunamiRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminInteropRoute: typeof AdminInteropRoute
  AdminObservabilidadRoute: typeof AdminObservabilidadRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ReportesIdRoute: typeof ReportesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tsunami': {
      id: '/tsunami'
      path: '/tsunami'
      fullPath: '/tsunami'
      preLoaderRoute: typeof TsunamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-es': {
      id: '/que-es'
      path: '/que-es'
      fullPath: '/que-es'
      preLoaderRoute: typeof QueEsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesidades': {
      id: '/necesidades'
      path: '/necesidades'
      fullPath: '/necesidades'
      preLoaderRoute: typeof NecesidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar': {
      id: '/donar'
      path: '/donar'
      fullPath: '/donar'
      preLoaderRoute: typeof DonarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos': {
      id: '/desaparecidos'
      path: '/desaparecidos'
      fullPath: '/desaparecidos'
      preLoaderRoute: typeof DesaparecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/$id': {
      id: '/reportes/$id'
      path: '/reportes/$id'
      fullPath: '/reportes/$id'
      preLoaderRoute: typeof ReportesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tsunami': {
      id: '/api/tsunami'
      path: '/tsunami'
      fullPath: '/api/tsunami'
      preLoaderRoute: typeof ApiTsunamiRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/reports.geojson': {
      id: '/api/reports.geojson'
      path: '/reports.geojson'
      fullPath: '/api/reports.geojson'
      preLoaderRoute: typeof ApiReportsDotgeojsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/reports.csv': {
      id: '/api/reports.csv'
      path: '/reports.csv'
      fullPath: '/api/reports.csv'
      preLoaderRoute: typeof ApiReportsDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/patients.json': {
      id: '/api/patients.json'
      path: '/patients.json'
      fullPath: '/api/patients.json'
      preLoaderRoute: typeof ApiPatientsDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/patients.csv': {
      id: '/api/patients.csv'
      path: '/patients.csv'
      fullPath: '/api/patients.csv'
      preLoaderRoute: typeof ApiPatientsDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/offers.json': {
      id: '/api/offers.json'
      path: '/offers.json'
      fullPath: '/api/offers.json'
      preLoaderRoute: typeof ApiOffersDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/offers.geojson': {
      id: '/api/offers.geojson'
      path: '/offers.geojson'
      fullPath: '/api/offers.geojson'
      preLoaderRoute: typeof ApiOffersDotgeojsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/offers.csv': {
      id: '/api/offers.csv'
      path: '/offers.csv'
      fullPath: '/api/offers.csv'
      preLoaderRoute: typeof ApiOffersDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/needs.json': {
      id: '/api/needs.json'
      path: '/needs.json'
      fullPath: '/api/needs.json'
      preLoaderRoute: typeof ApiNeedsDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/needs.geojson': {
      id: '/api/needs.geojson'
      path: '/needs.geojson'
      fullPath: '/api/needs.geojson'
      preLoaderRoute: typeof ApiNeedsDotgeojsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/needs.csv': {
      id: '/api/needs.csv'
      path: '/needs.csv'
      fullPath: '/api/needs.csv'
      preLoaderRoute: typeof ApiNeedsDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/missing-persons.json': {
      id: '/api/missing-persons.json'
      path: '/missing-persons.json'
      fullPath: '/api/missing-persons.json'
      preLoaderRoute: typeof ApiMissingPersonsDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/missing-persons.geojson': {
      id: '/api/missing-persons.geojson'
      path: '/missing-persons.geojson'
      fullPath: '/api/missing-persons.geojson'
      preLoaderRoute: typeof ApiMissingPersonsDotgeojsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/missing-persons.csv': {
      id: '/api/missing-persons.csv'
      path: '/missing-persons.csv'
      fullPath: '/api/missing-persons.csv'
      preLoaderRoute: typeof ApiMissingPersonsDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/health-centers.json': {
      id: '/api/health-centers.json'
      path: '/health-centers.json'
      fullPath: '/api/health-centers.json'
      preLoaderRoute: typeof ApiHealthCentersDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/health-centers.geojson': {
      id: '/api/health-centers.geojson'
      path: '/health-centers.geojson'
      fullPath: '/api/health-centers.geojson'
      preLoaderRoute: typeof ApiHealthCentersDotgeojsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/health-centers.csv': {
      id: '/api/health-centers.csv'
      path: '/health-centers.csv'
      fullPath: '/api/health-centers.csv'
      preLoaderRoute: typeof ApiHealthCentersDotcsvRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/categories.json': {
      id: '/api/categories.json'
      path: '/categories.json'
      fullPath: '/api/categories.json'
      preLoaderRoute: typeof ApiCategoriesDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/admin/observabilidad': {
      id: '/admin/observabilidad'
      path: '/admin/observabilidad'
      fullPath: '/admin/observabilidad'
      preLoaderRoute: typeof AdminObservabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/interop': {
      id: '/admin/interop'
      path: '/admin/interop'
      fullPath: '/admin/interop'
      preLoaderRoute: typeof AdminInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reports': {
      id: '/api/public/reports'
      path: '/public/reports'
      fullPath: '/api/public/reports'
      preLoaderRoute: typeof ApiPublicReportsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/geocode': {
      id: '/api/public/geocode'
      path: '/public/geocode'
      fullPath: '/api/public/geocode'
      preLoaderRoute: typeof ApiPublicGeocodeRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof ApiRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/push/manage': {
      id: '/api/public/push/manage'
      path: '/public/push/manage'
      fullPath: '/api/public/push/manage'
      preLoaderRoute: typeof ApiPublicPushManageRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/push/broadcast': {
      id: '/api/public/push/broadcast'
      path: '/public/push/broadcast'
      fullPath: '/api/public/push/broadcast'
      preLoaderRoute: typeof ApiPublicPushBroadcastRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/hooks/ingest-usgs': {
      id: '/api/public/hooks/ingest-usgs'
      path: '/public/hooks/ingest-usgs'
      fullPath: '/api/public/hooks/ingest-usgs'
      preLoaderRoute: typeof ApiPublicHooksIngestUsgsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/admin/health': {
      id: '/api/public/admin/health'
      path: '/public/admin/health'
      fullPath: '/api/public/admin/health'
      preLoaderRoute: typeof ApiPublicAdminHealthRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiCategoriesDotjsonRoute: typeof ApiCategoriesDotjsonRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiHealthCentersDotcsvRoute: typeof ApiHealthCentersDotcsvRoute
  ApiHealthCentersDotgeojsonRoute: typeof ApiHealthCentersDotgeojsonRoute
  ApiHealthCentersDotjsonRoute: typeof ApiHealthCentersDotjsonRoute
  ApiMissingPersonsDotcsvRoute: typeof ApiMissingPersonsDotcsvRoute
  ApiMissingPersonsDotgeojsonRoute: typeof ApiMissingPersonsDotgeojsonRoute
  ApiMissingPersonsDotjsonRoute: typeof ApiMissingPersonsDotjsonRoute
  ApiNeedsDotcsvRoute: typeof ApiNeedsDotcsvRoute
  ApiNeedsDotgeojsonRoute: typeof ApiNeedsDotgeojsonRoute
  ApiNeedsDotjsonRoute: typeof ApiNeedsDotjsonRoute
  ApiOffersDotcsvRoute: typeof ApiOffersDotcsvRoute
  ApiOffersDotgeojsonRoute: typeof ApiOffersDotgeojsonRoute
  ApiOffersDotjsonRoute: typeof ApiOffersDotjsonRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiPatientsDotcsvRoute: typeof ApiPatientsDotcsvRoute
  ApiPatientsDotjsonRoute: typeof ApiPatientsDotjsonRoute
  ApiReportsDotcsvRoute: typeof ApiReportsDotcsvRoute
  ApiReportsDotgeojsonRoute: typeof ApiReportsDotgeojsonRoute
  ApiTsunamiRoute: typeof ApiTsunamiRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicGeocodeRoute: typeof ApiPublicGeocodeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicReportsRoute: typeof ApiPublicReportsRoute
  ApiPublicAdminHealthRoute: typeof ApiPublicAdminHealthRoute
  ApiPublicHooksIngestUsgsRoute: typeof ApiPublicHooksIngestUsgsRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicPushBroadcastRoute: typeof ApiPublicPushBroadcastRoute
  ApiPublicPushManageRoute: typeof ApiPublicPushManageRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiCategoriesDotjsonRoute: ApiCategoriesDotjsonRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiHealthCentersDotcsvRoute: ApiHealthCentersDotcsvRoute,
  ApiHealthCentersDotgeojsonRoute: ApiHealthCentersDotgeojsonRoute,
  ApiHealthCentersDotjsonRoute: ApiHealthCentersDotjsonRoute,
  ApiMissingPersonsDotcsvRoute: ApiMissingPersonsDotcsvRoute,
  ApiMissingPersonsDotgeojsonRoute: ApiMissingPersonsDotgeojsonRoute,
  ApiMissingPersonsDotjsonRoute: ApiMissingPersonsDotjsonRoute,
  ApiNeedsDotcsvRoute: ApiNeedsDotcsvRoute,
  ApiNeedsDotgeojsonRoute: ApiNeedsDotgeojsonRoute,
  ApiNeedsDotjsonRoute: ApiNeedsDotjsonRoute,
  ApiOffersDotcsvRoute: ApiOffersDotcsvRoute,
  ApiOffersDotgeojsonRoute: ApiOffersDotgeojsonRoute,
  ApiOffersDotjsonRoute: ApiOffersDotjsonRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiPatientsDotcsvRoute: ApiPatientsDotcsvRoute,
  ApiPatientsDotjsonRoute: ApiPatientsDotjsonRoute,
  ApiReportsDotcsvRoute: ApiReportsDotcsvRoute,
  ApiReportsDotgeojsonRoute: ApiReportsDotgeojsonRoute,
  ApiTsunamiRoute: ApiTsunamiRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicGeocodeRoute: ApiPublicGeocodeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicReportsRoute: ApiPublicReportsRoute,
  ApiPublicAdminHealthRoute: ApiPublicAdminHealthRoute,
  ApiPublicHooksIngestUsgsRoute: ApiPublicHooksIngestUsgsRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicPushBroadcastRoute: ApiPublicPushBroadcastRoute,
  ApiPublicPushManageRoute: ApiPublicPushManageRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRouteWithChildren,
  AuthRoute: AuthRoute,
  CreditosRoute: CreditosRoute,
  DesaparecidosRoute: DesaparecidosRoute,
  DonarRoute: DonarRoute,
  EstadisticasRoute: EstadisticasRoute,
  NecesidadesRoute: NecesidadesRoute,
  OfertasRoute: OfertasRoute,
  PacientesRoute: PacientesRoute,
  QueEsRoute: QueEsRoute,
  ReportarRoute: ReportarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TsunamiRoute: TsunamiRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminInteropRoute: AdminInteropRoute,
  AdminObservabilidadRoute: AdminObservabilidadRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ReportesIdRoute: ReportesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
